### ISSUE TITLE
Relude dependency

### ISSUE THREAD

**Issue by ju1m** [srid/lvar#3]
Just to give you a heads-up, [`Relude` is currently broken with GHC 9.4](https://github.com/kowainik/relude/pull/421), hence so is `lvar` since https://github.com/srid/lvar/commit/e68489533fcb67b7404c945b443bb58cdc23b710.
It may be wise to avoid depending upon `Relude` in a (simple) library.

**Comment by srid** [comment]
Agreed, and PR welcome!

**Comment by ju1m** [comment]
Sorry I'll pass, I'm just reviewing available libraries, I'm not actually using `lvar` so far.

**Comment by mmhat** [comment]
I believe the issue was resolved upstream and this issue can be closed?
